# Generated by Django 5.2.7 on 2025-11-07 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название турнира"),
                ),
                ("date", models.DateField(verbose_name="Дата проведения")),
                (
                    "location",
                    models.CharField(max_length=300, verbose_name="Место проведения"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "rules",
                    models.TextField(blank=True, null=True, verbose_name="Правила"),
                ),
                (
                    "registration_open",
                    models.BooleanField(
                        default=False, verbose_name="Регистрация открыта"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Турнир активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tournaments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Турнир",
                "verbose_name_plural": "Турниры",
                "ordering": ["-date"],
            },
        ),
    ]
