# Generated by Django 5.2.7 on 2025-11-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentGrid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grid_type",
                    models.CharField(
                        choices=[
                            (
                                "single_elimination",
                                "Олимпийская система (на выбывание)",
                            ),
                            ("double_elimination", "Двойная олимпийская система"),
                            ("round_robin", "Круговая система"),
                        ],
                        default="single_elimination",
                        max_length=30,
                        verbose_name="Тип сетки",
                    ),
                ),
                (
                    "is_generated",
                    models.BooleanField(
                        default=False, verbose_name="Сетка сгенерирована"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grid",
                        to="Category.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Турнирная сетка",
                "verbose_name_plural": "Турнирные сетки",
                "db_table": "tournament_grid",
            },
        ),
    ]
