# Generated by Django 5.2.7 on 2025-11-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Tournament", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название категории"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                ("age_min", models.IntegerField(verbose_name="Минимальный возраст")),
                ("age_max", models.IntegerField(verbose_name="Максимальный возраст")),
                (
                    "weight_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Минимальный вес (кг)",
                    ),
                ),
                (
                    "weight_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Максимальный вес (кг)",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Начинающий"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                            ("professional", "Профессионал"),
                        ],
                        max_length=20,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="Tournament.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "category",
                "ordering": ["age_min", "weight_min"],
            },
        ),
    ]
