# Generated by Django 5.2.7 on 2025-11-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Match", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField(verbose_name="Время начала")),
                ("mat_number", models.IntegerField(verbose_name="Номер мата")),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=5, verbose_name="Продолжительность (мин)"
                    ),
                ),
                (
                    "is_started",
                    models.BooleanField(default=False, verbose_name="Начался"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Завершён"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="Match.match",
                        verbose_name="Поединок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписания",
                "db_table": "schedule",
                "ordering": ["scheduled_time", "mat_number"],
            },
        ),
    ]
