# Generated by Django 5.2.7 on 2025-11-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Athlete", "0001_initial"),
        ("TournamentGrid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round",
                    models.CharField(
                        choices=[
                            ("final", "Финал"),
                            ("semifinal", "Полуфинал"),
                            ("quarterfinal", "Четвертьфинал"),
                            ("round_of_16", "1/8 финала"),
                            ("round_of_32", "1/16 финала"),
                            ("preliminary", "Предварительный раунд"),
                        ],
                        max_length=20,
                        verbose_name="Раунд",
                    ),
                ),
                ("match_number", models.IntegerField(verbose_name="Номер боя")),
                (
                    "score_athlete1",
                    models.IntegerField(default=0, verbose_name="Счёт спортсмена 1"),
                ),
                (
                    "score_athlete2",
                    models.IntegerField(default=0, verbose_name="Счёт спортсмена 2"),
                ),
                (
                    "result_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submission", "Сабмишн"),
                            ("points", "По очкам"),
                            ("disqualification", "Дисквалификация"),
                            ("technical", "Техническая победа"),
                            ("walkover", "Неявка соперника"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Способ победы",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Завершён"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "athlete1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_athlete1",
                        to="Athlete.athlete",
                        verbose_name="Спортсмен 1",
                    ),
                ),
                (
                    "athlete2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_athlete2",
                        to="Athlete.athlete",
                        verbose_name="Спортсмен 2",
                    ),
                ),
                (
                    "grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="TournamentGrid.tournamentgrid",
                        verbose_name="Сетка",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_matches",
                        to="Athlete.athlete",
                        verbose_name="Победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поединок",
                "verbose_name_plural": "Поединки",
                "db_table": "match",
                "ordering": ["match_number"],
            },
        ),
    ]
